server:
  port: 8092

spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paycore_audit
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
