server:
  port: 8086

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paycore_auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

# gRPC Server Settings
grpc:
  server:
    port: 50056

# Actuator & Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
