server:
  port: 8091

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paycore_notification
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
